FROM python:3.11

RUN pip install poetry

WORKDIR /code
COPY ./pyproject.toml ./poetry.lock*  /code/

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY . .
CMD ["arq", "src.jobs.scheduler.schedulerSettings"]