services:
  arq:
    build:
      context: .
      dockerfile: dockerfile.scheduler
    restart: always
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
networks:
  traefik-public:
    external: false
